export const mock = {
  id: 1,
  name: 'Joao Josten',
  photo: 'http://www.pudim.com.br/pudim.jpg',
  birthDate: 2000,
  job: 'Programador',
  birthPlace: 'Atlantis',
  extras: 'Um menino sonhador',
  father: {
    id: 2,
    name: 'Jonas Josten',
    photo: 'http://www.pudim.com.br/pudim.jpg',
    birthDate: 1970,
    job: 'Salva Vidas',
    birthPlace: 'Nova Yorque',
    deathPlace: 'Atlantis',
    deathDate: 2002,
    extras: 'Morreu Afogado após tentar salvar um tubarão de um submarino',
    father: {
      id: 3,
      name: 'Joaquim Josten',
      photo: 'http://www.pudim.com.br/pudim.jpg',
    },
    mother: {
      id: 6,
      name: 'Maria das Hortas',
      photo: 'http://www.pudim.com.br/pudim.jpg',
    },
  },
  mother: {
    id: 7,
    name: 'Joana Josten',
    birthDate: 1972,
    job: 'Ex Jogadora de WoW',
    birthPlace: 'Atlantis',
    extras: 'Adora jogar Street Fighter',
    photo: 'http://www.pudim.com.br/pudim.jpg',
    father: {
      id: 8,
      name: 'Giovane Giorno',
      photo: 'http://www.pudim.com.br/pudim.jpg',
    },
    mother: {
      id: 9,
      name: 'Cruzalda das flores',
      photo: 'http://www.pudim.com.br/pudim.jpg',
    },
  },
};
